# -*- coding: utf-8 -*-
"""Abstractive Summarization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11jAI4b6xGG9_3BfW1CAQP2xlKri1luJH
"""

# !pip install transformers

from transformers import pipeline
from bs4 import BeautifulSoup
import requests

"""# Load Summarization Pipeline

---


"""

summarizer = pipeline("summarization")

"""# Get Articles"""

URL = "https://zeenews.india.com/india/manipur-violence-supreme-court-directs-state-govt-to-file-fresh-status-report-on-meitei-kuki-clashes-2609239.html"
# URL = "https://www.thehindu.com/news/national/mea-rejects-state-department-report-citing-deteriorating-religious-freedom-in-india/article66858851.ece"
# URL = "https://www.indiatoday.in/india/story/jaishankar-russian-oil-import-refined-fuel-eu-foreign-policy-chief-josep-borrell-council-regulations-brussels-2380190-2023-05-17"

r = requests.get(URL)

soup = BeautifulSoup(r.text, 'html.parser')
results = soup.find_all(['h1', 'p'])
text = [result.text for result in results]
ARTICLE = ' '.join(text)

ARTICLE

"""# Chunk Text"""

max_chunk = 500

ARTICLE = ARTICLE.replace('.', '.<eos>')
ARTICLE = ARTICLE.replace('?', '?<eos>')
ARTICLE = ARTICLE.replace('!', '!<eos>')

sentences = ARTICLE.split('<eos>')
current_chunk = 0 
chunks = []
for sentence in sentences:
    if len(chunks) == current_chunk + 1: 
        if len(chunks[current_chunk]) + len(sentence.split(' ')) <= max_chunk:
            chunks[current_chunk].extend(sentence.split(' '))
        else:
            current_chunk += 1
            chunks.append(sentence.split(' '))
    else:
        chunks.append(sentence.split(' '))

for chunk_id in range(len(chunks)):
    chunks[chunk_id] = ' '.join(chunks[chunk_id])

"""# Summarize Text"""

res = summarizer(chunks, max_length=65, min_length=30, do_sample=False)

res[0]

' '.join([summ['summary_text'] for summ in res])

text = ' '.join([summ['summary_text'] for summ in res])

text

"""# Output to Text File"""

with open('summary.txt', 'w') as f:
    f.write(text)

