# -*- coding: utf-8 -*-
"""Extractive Summarizer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14csZgX2kI7tvcia7jutenUzJFd-ZLFl9
"""

# importing libraries


from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize

text = """By any standard, 2022 was a year of crises, including the continuing COVID-19 pandemic, war in Ukraine, worldwide inflation, and a range of local and global climate emergencies. We thus have more evidence about how life evaluations, trust and social connections together influence the ability of nations, and of the world as a whole, to adapt in the face of crisis. Our main analysis relates to happiness as measured by life evaluations and emotions, how they have evolved in crisis situations, and how lives have been better where trust, benevolence, and supportive social connections have continued to thrive.

In our first section, we present our annual ranking and modelling of national happiness, but in a way slightly different from previous practice. Our key figure 2.1 continues to rank countries by their average life evaluations over the three preceding years, with that average spanning the three COVID-19 years of 2020-2022. That much remains the same. The main change is that this year we have removed the coloured sub-bars showing our attempts to explain the differences we find in national happiness. We introduced these bars in 2013 because readers wanted to know more about some of the likely reasons behind the large differences we find. Over the succeeding years, however, many readers and commentators have thereby been led to think that our ranking somehow reflects an index based on the six variables we use in our modelling. To help correct this false impression, we removed the explanatory bars, leaving the actual life evaluations alone on centre stage. We continue to include horizontal whiskers showing the 95% confidence bands for our national estimates, supplemented this year by showing a measure for each country of the range of rankings within which its own ranking is likely to be. We also continue to present our attempts to explain how and why life evaluations vary among countries and over time. We then present our latest attempts to explain the happiness differences revealed by the wide variations in national life evaluations.

In our second section, we look back once again at the evolution of life evaluations and emotions since Gallup World Poll data first became available in 2005-2006. This year we focus especially on how COVID-19 has affected the distribution of well-being. Has well-being inequality grown or shrunk? Where, and for whom? We divide national populations into their happier and less happy halves to show how the two groups have fared before and during the pandemic. We do this for life evaluations, and for their emotional, social, and material foundations.

In the third section, we document the extent to which trust, benevolence, and social connections have supported well-being in times of crisis. First we add a third year of COVID-19 data to illustrate how much death rate patterns changed in 2022 under the joint influences of Omicron variants, widespread vaccination, and changes in public health measures. Countries where people have confidence in their governments were still able to have lower COVID-19 death tolls in 2022, just as they did in 2020 and 2021.

Next we update our reporting on the extent to which benevolence has increased during COVID-19, finding it still well above pre-pandemic levels.

Then we present data on how the conflict between Ukraine and Russia since 2014, and especially in 2022, is associated with patterns of life evaluations, emotions, trust in governments, and benevolence in both countries.

Finally, we leverage new data from 2022 on the relative importance of positive and negative aspects of the social context. These data show that positive social environments were far more prevalent than loneliness and that gains from increases in positive social connections exceed the well-being costs of additional loneliness, even during COVID-19. These findings help us explain the resilience of life evaluations. While crises impose undoubted costs, they may also expose and even build a sense of shared connections.

Our concluding section provides a summary of our key results."""

# Tokenizing the text
stopWords = set(stopwords.words("english"))
words = word_tokenize(text)

# Creating a frequency table to keep the
# score of each word

freqTable = dict()
for word in words:
    word = word.lower()
    if word in stopWords:
        continue
    if word in freqTable:
        freqTable[word] += 1
    else:
        freqTable[word] = 1

# Creating a dictionary to keep the score
# of each sentence
sentences = sent_tokenize(text)
sentenceValue = dict()

for sentence in sentences:
    for word, freq in freqTable.items():
        if word in sentence.lower():
            if sentence in sentenceValue:
                sentenceValue[sentence] += freq
            else:
                sentenceValue[sentence] = freq


# print(sentenceValue)
sumValues = 0
for sentence in sentenceValue:
    sumValues += sentenceValue[sentence]

# Average value of a sentence from the original text

average = int(sumValues / len(sentenceValue))

# Storing sentences into our summary.
summary = ''
for sentence in sentences:
    if (sentence in sentenceValue) and (sentenceValue[sentence] > (1.2 * average)):
        summary += " " + sentence
print(summary)

